name: autooed
channels:
  - defaults
dependencies:
  - pip=20.1.1
  - python=3.7.7
  - setuptools=47.3.1
  - sqlite=3.32.3
  - tk=8.6.10
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - autograd==1.3
    - cma==3.0.3
    - cycler==0.10.0
    - cython==0.29.20
    - dill==0.3.3
    - future==0.18.2
    - joblib==0.16.0
    - kiwisolver==1.2.0
    - matplotlib==3.2.2
    - multiprocess==0.70.11.1
    - numpy==1.20.0
    - pandas==1.0.5
    - pillow==8.1.1
    - pydoe2==1.3.0
    - pymop==0.2.4
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2020.1
    - pyyaml==5.4
    - requests==2.23.0
    - scikit-learn==0.23.1
    - scipy==1.5.1
    - six==1.15.0
    - sklearn==0.0
    - threadpoolctl==2.1.0
    - tkintertable==1.3.2
    - torch==1.10.0